// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoNnBMtJfrwNqtkGwbLd6WWEtxivYJUTQ',
    appId: '1:389860386243:web:4f389fb96026d7a9534976',
    messagingSenderId: '389860386243',
    projectId: 'gps-semovil',
    authDomain: 'gps-semovil.firebaseapp.com',
    storageBucket: 'gps-semovil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBdGYTPocGBX1YMVB5xe71C0QVXmdhspc',
    appId: '1:389860386243:android:c3d122e223905a93534976',
    messagingSenderId: '389860386243',
    projectId: 'gps-semovil',
    storageBucket: 'gps-semovil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXtCNP2VKxBAhVyDkm2xe7nbiV29o348A',
    appId: '1:389860386243:ios:22eef9371c6744f3534976',
    messagingSenderId: '389860386243',
    projectId: 'gps-semovil',
    storageBucket: 'gps-semovil.appspot.com',
    iosBundleId: 'mx.edu.ittepic.gpsSemovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXtCNP2VKxBAhVyDkm2xe7nbiV29o348A',
    appId: '1:389860386243:ios:a2000fdbbe3689dd534976',
    messagingSenderId: '389860386243',
    projectId: 'gps-semovil',
    storageBucket: 'gps-semovil.appspot.com',
    iosBundleId: 'mx.edu.ittepic.gpsSemovil.RunnerTests',
  );
}
